apiVersion: github.coop.no/v1alpha1
kind: RepositoryConfig
metadata:
  name: member-lib
spec:
  description: "Member & Partner Team's Go: Crafted abstract packages for various use cases to enhance productivity and eliminate redundancy."

  branches:
    default: main
    protection:
      - id: main
        pattern: main
        requireSignedCommits: false
        requiredStatusChecks:
          checks:
            - "build"
        requiredPullRequestReviews:
          requireCodeOwnerReviews: true